# Generated by Django 4.2.13 on 2024-05-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                ("delivery_date", models.DateField(verbose_name="Date")),
                ("name", models.CharField(max_length=40, verbose_name="Full Name:")),
                ("email", models.CharField(max_length=40, verbose_name="Email:")),
                (
                    "phone",
                    models.CharField(max_length=11, verbose_name="Phone Number:"),
                ),
                (
                    "comments",
                    models.TextField(
                        max_length=1000, verbose_name="Additional Comments"
                    ),
                ),
                (
                    "delivery_time",
                    models.CharField(max_length=10, verbose_name="Delivery Time:"),
                ),
            ],
        ),
    ]
