# Generated by Django 4.2.13 on 2024-05-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="addorder",
            name="topping",
            field=models.CharField(
                choices=[
                    ("blu", "Blueberries"),
                    ("ban", "Bannana"),
                    ("mix", "Mixed Berries"),
                ],
                default="Default",
                max_length=14,
            ),
        ),
    ]
