# Generated by Django 4.2.13 on 2024-06-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_promotion_promotionusage"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="promotionusage", unique_together=set(),),
        migrations.AddField(
            model_name="promotionusage",
            name="name",
            field=models.CharField(
                default="none", max_length=40, verbose_name="Full Name:"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="promotionusage", unique_together={("promotion", "name")},
        ),
        migrations.RemoveField(model_name="promotionusage", name="user",),
    ]
