# Generated by Django 4.2.13 on 2024-06-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_promotionusage_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addorder",
            name="topping",
            field=models.CharField(
                choices=[
                    ("blu", "Blueberries"),
                    ("ban", "Bannana"),
                    ("mix", "Mixed Berries"),
                ],
                max_length=14,
            ),
        ),
    ]
